### PR TITLE
Add a workaround to wix.targets for v3 to support WiX 3.11 in VS2019

### PR DESCRIPTION
**Pull request by drolevar**

### CODE REVIEW

**Comment by chrpai** [comment]
I made a private build of Votive using @drolevar's ropos containing his msbuild pull request.  Tested  VS2019 Preview 1 with WiX 3.10, 3.11 and a private build of 3.14 and all the scenarios look good to me.

**Comment by chrpai** [comment]
The VS2019 extension that was released won't work for WiX 3.10/11 unless this PR is included.  It only currently works for unreleased/private builds of 3.14 currently.

**Comment by rseanhall** [comment]
The only reason this change is needed is because Microsoft made a breaking change in MSBuild - https://github.com/Microsoft/msbuild/issues/3778. Go there and ask when they'll complete the fallback logic if that's important to you. I don't think it's unreasonable for our preview extension to only work with our latest [v3.14 Weekly Build](http://wixtoolset.org/releases/weekly/).

**Comment by barnson** [comment]
@rseanhall Would you like to place a wager on whether the fallback logic ever gets implemented? That aside, it's not clear that the fallback logic is going to kick in for comparisons, or just use in a path.

**Comment by rseanhall** [comment]
I think there's a much lower chance of it happening if no one complains.

**Comment by robmen** [comment]
MSBuild fixed their "breaking change" and this is not necessary (thank goodness). Thanks anyway.

**Pull request closed without merging**
