### PR TITLE
Create a project for VS2019; fix integration with current WiX 3.11

### PR DESCRIPTION
**Pull request by drolevar**

### CODE REVIEW

**Comment by rseanhall** [comment]
We were planning on taking #7. Have you done something different from that pull request?

**Comment by drolevar** [comment]
> We were planning on taking #7. Have you done something different from that pull request?

The only difference I know of is a fix to wix.targets redirect for Wix v3, which allows using the current release v3.11. 
wix.targets in v3.11 assumes that $(MSBuildToolsVersion) is a number, which causes a crash in 2019 where it's defined as "Current".

**Comment by drolevar** [comment]
And, I've also fixed the WixLogoDev16.png to reference 2019.

Best regards,
Andrij Abyzov

**Comment by rseanhall** [comment]
Thanks! I integrated your changes in the `Create a project for VS2019` commit, but didn't take the fix for the WiX v3.11 imports. Can you resubmit that as a separate pull request? Also, I might be wrong but isn't that redirect.targets only picked up by versions of MSBuild > v4.0? If so, it wouldn't have to check the version of MSBuild.

**Comment by drolevar** [comment]
@rseanhall You're right. Made the fix and resubmitted the pull request.

**Pull request closed without merging**
