### PR TITLE
Add support for VS2022

### PR DESCRIPTION
**Pull request by drolevar**

### CODE REVIEW

**Comment by drolevar** [comment]
@robmen @virzak @jcassidyav
Was a bit tricky with 2022 but I finally got it working.
Had to upgrade all projects to ProjectReference because the newest Microsoft.VSSDK.BuildTools doesn't work with packages.config anymore.

**Comment by rkieslinger** [comment]
@drolevar Thx for your work so far!

Is there any time table, when the extension for VS 2022 will be finished? Will it support wix3 too?

**Comment by drolevar** [comment]
@rkieslinger This is the PR to support VS2022 in the existing extension, which is primarily intended for wix3.
So you can build it yourself and it will work like it does for me.
And building is no harder than cloning and then running
```
nuget restore
msbuild src\src.proj -p:Configuration=Release
```
from Visual Studio 2022 command prompt.
As for when and if this is going to be merged, that's not a question for me.

**Comment by jcassidyav** [comment]
Just to note that changes will be required for VS2022 in the wix3 and wix4 VSExtension bits if your installer is using the VS variables.

**Comment by drolevar** [comment]
Could you please elaborate on that?

**Comment by jcassidyav** [comment]
For example I could have an installer with the following
```
<?xml version="1.0" encoding="UTF-8"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi" xmlns:util="http://schemas.microsoft.com/wix/UtilExtension"  xmlns:vs="http://schemas.microsoft.com/wix/VSExtension">
	<Fragment>
    <PropertyRef Id="VS2019_EXTENSIONS_DIR" />
    
    <Property Id="NGEN2DIRXXX">
      <DirectorySearch Id="Windows" Path="[VS2019_EXTENSIONS_DIR]">
          <DirectorySearch Id="Ngen2Dir" Depth="2" AssignToProperty="yes">
            <FileSearch Id="Ngen_exe" Name="Some.dll" />
          </DirectorySearch>
      </DirectorySearch>
    </Property>

  </Fragment>
</Wix>
```

To fully support VS2022 I would need to be able to use say a VS2022_EXTENSIONS_DIR  property, these are provided by the VSExtension.

**Comment by drolevar** [comment]
@jcassidyav Those variables are defined by WiX itself, not by the Visual Studio extension.
I might consider making a patch for wix3, however, I'm absolutely not sure this PR will be accepted, since more or less all the development of wix3 is stopped now, unless @robmen decides otherwise.
Your best option is creating a patched fork of this WiX extension
https://github.com/wixtoolset/wix3/tree/develop/src/ext/VSExtension
and building it yourself (only the extension, not the whole WiX).

**Comment by robmen** [comment]
PS: I saw an update [after the comment about it being ready](https://github.com/wixtoolset/VisualStudioExtension/pull/21#issuecomment-926807859) so this got pushed to my backburner. 

I was going to get around to this PR when VS2022 was RTM and I upgraded or I had free cycles to install VS2022 into a VM and test it out.

So, @drolevar, thank you for doing this work. I need to reconcile it with #19 and I should have been clearer about what my plan was.

_PS: I'm (personally) working on being more active on GitHub. Even if it is just a comment to the effect, "I see you, thanks! I'll be back in a while to do something with this change."_

**Comment by robmen** [comment]
recheck

**Comment by drolevar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by drolevar** [comment]
recheck

**Comment by nil4** [comment]
@drolevar I really appreciate your work on getting Votive ready for VS 2022! 

I managed to build the Votive2022 VSIX using your instructions above https://github.com/wixtoolset/VisualStudioExtension/pull/21#issuecomment-941993603, and can confirm it installs and works.

While building, I did run into one minor issue, related to https://github.com/drolevar/VisualStudioExtension/blob/f07ba11fa5a1c6fd98a65957468e78a6c7d12964/tools/WixBuild.Tools.targets#L16. This reference to `Microsoft.Build.Tasks` version 2.0 appears to be a .NET 2.0 / 3.5 assembly. 

On Windows 11, with only VS 2022 RC2 installed, .the NET Framework 3.5 OS feature is *not* enabled by default, and the reference cannot be resolved. Updating it to the equivalent MSBuild 17.0 task assembly seemed to do the trick, and allowed the Votive build to succeed:

```diff
-<UsingTask TaskName="AssignTargetPath" AssemblyName="Microsoft.Build.Tasks, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
+<UsingTask TaskName="AssignTargetPath" AssemblyName="Microsoft.Build.Tasks.Core, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
```

I hope this might help others who run into this.

**Comment by StevenBonePgh** [comment]
The one fear I had with Wix was the bitness of MSBuild causing problems here or there. After Rick A helped me compile this PR into a VSIX 👍 I tested some projects, and yeah, I think I am being bit by this one.

In my .wixproj I have `<Target Name="BeforeBuild">` with `<HeatDirectory>`. This unfortunately crashes Visual Studio when it builds the project with the following stack trace:

> Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   at System.Reflection.Assembly.LoadFrom(System.String)
   at Microsoft.Tools.WindowsInstallerXml.Build.Tasks.WixToolTask.ExecuteToolThread(System.Object)

Removing `<HeatDirectory>` prevents the crash, but is not desired, obviously.

The solution would normally be to add `<RunWixToolsOutOfProc>true</RunWixToolsOutOfProc>` to the .wixproj file in the top unconditioned `PropertyGroup`. This does not seem to have any impact and VS crashes with same stack trace. I am kind of surprised that Visual Studio would crash as I thought this would be all MSBuild.  Is Votive somehow involved in a build?  I suppose getting ProjectTools and trying a binary msbuild log would be the next step to see what is being passed to the build task. Does anyone have a better idea of how to troubleshoot this one?  

### Update
As I suspected, this is not a Votive issue, but a Wix Toolset issue. If you add `RunAsSeparateProcess="true"` attribute to the `<HeatDirectory>` element, this will work around the crash by not attempting to load the x86 `heat.exe` in-proc. As Wix 3.14 is .NET 4.5, perhaps setting the tools to be 'Any CPU' with 'Prefer 32-bit' would be a solution to this without resorting to a change to project files. Alternatively, or in addition to based on the viability of the tool being x64 compatible or for a 3.11 rather than 3.14 patch, `WixTasks` class `WixToolTask.RunAsSeparateProcess` property getter could be altered to infer a setting of `true` if the Task is running as 64-bit. @robmen What sort of PR(s) would you be willing to accept on this? Also, how is `RunWixToolsOutOfProc` intended to work - can't find a good reference on this.

**Comment by mtissington** [comment]
I'm trying to build visual studio extension myself and I'm told I need to first build this
`OneTimeWixBuildInitialization.proj` from an admin prompt.

And when I try to do that I get the following
 `error : Could not find sn.exe. Expected to find it at: \bin\sn.exe`

I assume this is the extension folder?
The only file in this folder is nuget.exe

What do I need to do?

**Comment by mtissington** [comment]
Struggling to build this ...

    nuget restore
    msbuild src\src.proj -p:Configuration=Release

When I do the above from a VS 2022 cmd prompt I get loads of errors (2000+) related to votive.shared so I guess I'm missing something, just no idea what.

`  C:\GitHub\wixtoolset\VisualStudioExtension\src\votive.shared\ProjectBase\UpdateSolutionEventsListener.cs(177,43): err
or CS0246: The type or namespace name 'IVsHierarchy' could not be found (are you missing a using directive or an assemb
ly reference?) [C:\GitHub\wixtoolset\VisualStudioExtension\src\Votive2022\Votive2022.csproj]
  C:\GitHub\wixtoolset\VisualStudioExtension\src\votive.shared\ProjectBase\UpdateSolutionEventsListener.cs(177,67): err
or CS0246: The type or namespace name 'IVsCfg' could not be found (are you missing a using directive or an assembly ref
erence?) [C:\GitHub\wixtoolset\VisualStudioExtension\src\Votive2022\Votive2022.csproj]
  C:\GitHub\wixtoolset\VisualStudioExtension\src\votive.shared\ProjectBase\UpdateSolutionEventsListener.cs(177,89): err
or CS0246: The type or namespace name 'IVsCfg' could not be found (are you missing a using directive or an assembly ref
erence?) [C:\GitHub\wixtoolset\VisualStudioExtension\src\Votive2022\Votive2022.csproj]
  C:\GitHub\wixtoolset\VisualStudioExtension\src\votive.shared\ProjectBase\UpdateSolutionEventsListener.cs(193,50): err
or CS0246: The type or namespace name 'IVsHierarchy' could not be found (are you missing a using directive or an assemb
ly reference?) [C:\GitHub\wixtoolset\VisualStudioExtension\src\Votive2022\Votive2022.csproj]
  C:\GitHub\wixtoolset\VisualStudioExtension\src\votive.shared\ProjectBase\UpdateSolutionEventsListener.cs(193,74): err
or CS0246: The type or namespace name 'IVsCfg' could not be found (are you missing a using directive or an assembly ref
erence?) [C:\GitHub\wixtoolset\VisualStudioExtension\src\Votive2022\Votive2022.csproj]
  C:\GitHub\wixtoolset\VisualStudioExtension\src\votive.shared\ProjectBase\UpdateSolutionEventsListener.cs(193,96): err
or CS0246: The type or namespace name 'IVsCfg' could not be found (are you missing a using directive or an assembly ref
erence?) [C:\GitHub\wixtoolset\VisualStudioExtension\src\Votive2022\Votive2022.csproj]
  C:\GitHub\wixtoolset\VisualStudioExtension\src\votive.shared\ProjectBase\UpdateSolutionEventsListener.cs(45,17): erro
r CS0246: The type or namespace name 'IVsSolutionBuildManager2' could not be found (are you missing a using directive o
r an assembly reference?) [C:\GitHub\wixtoolset\VisualStudioExtension\src\Votive2022\Votive2022.csproj]`

**Comment by drolevar** [comment]
That's normally a sign that nuget restore didn't work properly.

**Comment by butler1233** [comment]
+1 Looks good to me. However I did have some issues with the "one time configuration" .proj to add the signing validation skipping, the value is added so the default registry location, but then the build check checks against that location and also the Wow6432Node version too, which didn't have it. Manually adding it sorted that though.

You can just bang the following in a .reg to fix that problem if you have it:

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\StrongName]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\StrongName\Verification]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\StrongName\Verification\*,ce35f76fcda82bad]
```

Other than that though mine build no problem using the latest changes posted a few hours ago. Seems to work fine.

**Comment by corykroll** [comment]
I'm trying to build this, and am stuck in the one time configuration as well.  
I opened this pull request and went straight to trying to build the Votive2022 project.  I get this error

`Strong name validation for the WiX toolset must be disabled on a developer machine to build. Execute 'msbuild C:\Users\Cory\source\repos\wixtoolset\VisualStudioExtension\Tools\OneTimeWixBuildInitialization.proj' from an elevated command prompt`

Opened a 'x86 Native Tools Command Prompt for VS 2019' in administrator mode (I have VS 2019 and VS 2022 installed btw) and I'm getting the following issue.  I'm not sure what sn.exe is or how to install or path to it.  Any help would be appreciated.

```
Project "C:\Users\Cory\source\repos\wixtoolset\VisualStudioExtension\Tools\OneTimeWixBuildInitialization.proj" on node
1 (default targets).
C:\Users\Cory\source\repos\wixtoolset\VisualStudioExtension\Tools\OneTimeWixBuildInitialization.proj(30,5): error : Cou
ld not find sn.exe. Expected to find it at: \bin\sn.exe
Done Building Project "C:\Users\Cory\source\repos\wixtoolset\VisualStudioExtension\Tools\OneTimeWixBuildInitialization.
proj" (default targets) -- FAILED.


Build FAILED.

"C:\Users\Cory\source\repos\wixtoolset\VisualStudioExtension\Tools\OneTimeWixBuildInitialization.proj" (default target)
 (1) ->
(RegisterStrongNameSkip target) ->
  C:\Users\Cory\source\repos\wixtoolset\VisualStudioExtension\Tools\OneTimeWixBuildInitialization.proj(30,5): error : C
ould not find sn.exe. Expected to find it at: \bin\sn.exe
```

**Comment by rokleM** [comment]
This is the version I've compiled, and I'm using right now. Don't make me responsible if your computer catches fire or does not work in any way after you install this. It works on my machine, yadda, yadda. 

[Votive2022.zip](https://github.com/wixtoolset/VisualStudioExtension/files/7522780/Votive2022.zip)

**Comment by corykroll** [comment]
> This is the version I've compiled, and I'm using right now. Don't make me responsible if your computer catches fire or does not work in any way after you install this. It works on my machine, yadda, yadda.
> 
> [Votive2022.zip](https://github.com/wixtoolset/VisualStudioExtension/files/7522780/Votive2022.zip)

The installer did work. but the WiX projects in my solution now say (incompatible) and I'm unable to use them.

**Comment by RuralRob** [comment]
> > This is the version I've compiled, and I'm using right now. Don't make me responsible if your computer catches fire or does not work in any way after you install this. It works on my machine, yadda, yadda.
> > [Votive2022.zip](https://github.com/wixtoolset/VisualStudioExtension/files/7522780/Votive2022.zip)
> 
> The installer did work. but the WiX projects in my solution now say (incompatible) and I'm unable to use them.

Ditto here!

**Comment by mediumharris** [comment]
My own build got rid of the (incompatible) after install and an unload\load for each project. I also have WiX Toolset v3.11 installed and added the .NET 3.5 Windows Feature (since Windows 11 does not add this by default and it was required to build properly).

**Comment by butler1233** [comment]
`sn.exe` is the .net assembly signing tool, which should be found in a folder along the lines of: 

`C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools`

It may require a workload that you don't have installed, though I'm not sure what that would be.

Here's the build I did the other day, which appears to work fine on my machine: 

## [Votive2022.zip](https://github.com/wixtoolset/VisualStudioExtension/files/7526774/Votive2022.zip)

*standard disclaimer applies, it's not my fault if you download binaries from random people on the internet and you end up getting a virus, third degree burns, a winning lottery ticket or exposure to a nuclear armageddon*

**Comment by barnson** [comment]
LGTM on RTM. :shipit:

**Pull request merged**
