### PR TITLE
Add support for VS2022

### PR DESCRIPTION
**Pull request by virzak**

### CODE REVIEW

**Comment by virzak** [comment]
Work in progress:

Can now compile votive2022.msix locally using:

`msbuild /p:Configuration=Release /p:TargetFrameworkVersion=v4.7.2 /p:CopyBuildOutputToOutputDirectory=true .\src\Votive2022\`

**Comment by drolevar** [comment]
@virzak I'm trying to build from your branch, but I can't do it from neither msbuild command line nor Visual Studio.
I understand it's a WIP but could you share how you do it?

**Comment by virzak** [comment]
@drolevar Try now. Compile in Visual Studio, then from command line and it should work.

Should be able to finish the draft on the weekend

**Comment by jcassidyav** [comment]
Is this still being worked on? it would be great to have this before launch of VS2020

**Comment by virzak** [comment]
@jcassidyav yeah, I was making good progress and then stuck, then ditched it lol. Let me take another stab at it.

**Comment by sfullerbeckman** [comment]
How is this PR coming? VS 2022 was released [today](https://visualstudio.microsoft.com/launch/).

**Comment by virzak** [comment]
Looks like #21 is way ahead of this PR. Tried using it with VS 2022 and it works great. You'll have to compile it yourself though.

**Comment by sfullerbeckman** [comment]
Can you explain how exactly I should compile and use this in my current project?

**Comment by virzak** [comment]
> 
> 
> Can you explain how exactly I should compile and use this in my current project?

You should ask that on #21 really.

I cloned that PR switched to the VS2022 branch, `nuget restore` and ran msbuild.

**Pull request closed without merging**
